const data2=
[
 {
    id:0,
    iconUrl:"/play.png",
    primaryColor:"#0A083E",
    benefitColor:"#0A083E",
    isRecommended:true,
    textColor:'#FFF',
    buttonColor:'#E73E88',
    buttonTextColor:'#F9E1F8',
    subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"430",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"300"} ,{time:'2 year',price:"500"},{time:'3 year',price:"750"}],
 },   
 {
    id:1,
    primaryColor:"#FFF",
    iconUrl:"/play-circle.png",
    textColor:'#0A083E',
    buttonColor:"#FAF2F7",
    buttonTextColor:'#E73E88',
    isRecommended:false,
    benefitColor:"#0A083E",
   subscriptionName:"Digital + Print",
   originalPrice:"1200",
   discount:"30",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"230",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives", 
  "Access to outlook archives",  
  "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"300"} ,{time:'2 year',price:"500"},{time:'3 year',price:"750"}],
 },   
 {
    id:2,
    primaryColor:"#FFF",
    iconUrl:"/play-circle.png",
    textColor:'#000',
    benefitColor:"#0A083E",
    isRecommended:'false',
    buttonColor:"#FAF2F7",
    buttonTextColor:'#E73E88',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"41120",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",
  "Access to outlook archives",  
  "Access to outlook archives",   
  ],
  tiers:
  [{time:"1 year",price:"300"} ,{time:'2 year',price:"500"},{time:'3 year',price:"750"}],
 },   
 {
    id:3,
    primaryColor:"#FFF",
    iconUrl:"/play-circle.png",
    textColor:'#000',
    isRecommended:'false',
    benefitColor:"#0A083E",
    buttonColor:"#FAF2F7",
    buttonTextColor:'#E73E88',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"4523230",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  "Doorstep delievery of print edition",
  "Access to outlook archives",    
],
  tiers:[{time:"1 year",price:"300"}],
},   
 {
    id:4,
    primaryColor:"#0A083E",
    iconUrl:"/play.png",
    benefitColor:"#0A083E",
    isRecommended:'false',
    textColor:'#FFF',
    buttonColor:'#E73E88',
    buttonTextColor:'#F9E1F8',
   subscriptionName:"Digital + Print",
   originalPrice:"978",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"450",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",
  "Access to outlook archives",  
  "Access to outlook archives",   
  ],
  tiers:
  [{time:"1 year",price:"300"} ,{time:'2 year',price:"500"},{time:'3 year',price:"750"}],
 },   
 {
    id:5,
    primaryColor:"#FFF",
    iconUrl:"/play-circle.png",
    textColor:'#000',
    benefitColor:"#0A083E",
    isRecommeded:'false',
    buttonColor:"#FAF2F7",
    buttonTextColor:'#E73E88',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"450",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives", 
  "Access to outlook archives",  
  "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"300"} ,{time:'2 year',price:"500"},{time:'3 year',price:"750"}],
 },   
]
export default data2;