const data4=
[{
    id:0,
    primaryColor:"#FFF",
    secondaryColor:'#5CA4EE',
    isRecommended:true,
    textColor:'#000',
    buttonColor:'#5CA4EE',
    buttonTextColor:'#FFF',
    subscriptionName:"Digital + Print",
    originalPrice:"900",
    discount:"50",
    benefitColor:'#9C9B9E',
    buttonPlaceholder:"SUBSCRIBE NOW",
  finalPrice:"450",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",
  "Doorstep delievery of print edition",
  "Access to outlook archives",      
  ],
  tiers:
  [{time:"1 year",price:"300",_id:0}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
 },   
 {
    id:1,
    isRecommended:false,
    primaryColor:'#223F80',
    secondaryColor:'#FFF',
    textColor:'#FFF',
    originalPrice:"900",
    buttonColor:'#F5F8FB',
    buttonTextColor:'#223F80',
    benefitColor:'#9FB5D6',
    discount:"50",
   subscriptionName:"DIGITAL + PRINT",
   buttonPlaceholder:"SUBSCRIBE NOW",
   benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  ],
  tiers:
  [{time:"1 year",price:"3340",_id:0} ,{time:'2 year',price:"500",_id:1},{time:'3 year',price:"750",_id:2}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
},   
 {
    id:2,
    primaryColor:"#223F80",
    secondaryColor:'#FFF',
    textColor:'#FFF',
    benefitColor:'#9FB5D6',
    buttonColor:'#F5F8FB',
    buttonTextColor:'#223F80',
    isRecommended:false,
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
   buttonPlaceholder:"SUBSCRIBE NOW",
   benefits:[
   "Access All Digital Features",
   "Doorstep delievery of print edition",
   "Access to outlook archives",  
   "Access to outlook archives",  
   "Access All Digital Features",
],
 tiers:[{time:"1 year",price:"3340",_id:0},{time:'2 year',price:"500",_id:1},{time:'3 year',price:"750",_id:2}], 
 offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
 },   
 {
    id:3,
    primaryColor:"#223F80",
    secondaryColor:'#FFF',
    isRecommended:false,
    textColor:'#FFF',
    buttonColor:'#F5F8FB',
    buttonTextColor:'#223F80',
    benefitColor:'#9FB5D6',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"SUBSCRIBE NOW",
  finalPrice:"450",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"3340",_id:0} ,{time:'2 year',price:"500",_id:1},{time:'3 year',price:"750",_id:2}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
 },   
 {
    id:4,
    primaryColor:"#FFF",
    secondaryColor:'#5CA4EE',
    textColor:'#000',
    isRecommended:false,
    benefitColor:'#9C9B9E',
    buttonColor:'#5CA4EE',
    buttonTextColor:'#FFF',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"SUBSCRIBE NOW",
  finalPrice:"450",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"34300",_id:0} ,{time:'2 year',price:"500",_id:1},{time:'3 year',price:"750",_id:2}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
},     
];
export default data4;