const data3=
[
 {
    id:0,
    primaryColor:"#BE0A1F",
    textColor:'#FFF',
    buttonColor:'#FFF',
    buttonTextColor:'#000',
    dropdownColor:'#880010',
    subscriptionName:"Digital + Print + E-paper + Mail",
    discount:"50",
    benefitColor:'#FFF',
    buttonPlaceholder:"Subscribe Now",
    finalPrice:"450",
    benefits:[
    "Access all digital features",
    "Doorstep delievery of print edition",
    "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"300"} ,{time:'2 year',price:"500"},{time:'3 year',price:"750"}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]  
},   
 {
    id:1,
    primaryColor:'#FFF',
    secondaryColor:"#FFF",
    buttonColor:'#000',
    buttonTextColor:'#FFF',
    dropdownColor:'#FFF',
    textColor:'#000',
    benefitColor:'#706C6E',
    subscriptionName:"Digital + Print",
    originalPrice:"1200",
    discount:"30",
    buttonPlaceholder:"Subscribe Now",
    finalPrice:"840",
    benefits:[
    "Access All Digital Features",
    "Doorstep delievery of print edition",
    "Access to outlook archives",  
    ],
  tiers:[{time:"1 year",price:"800"} ,{time:'2 year',price:"1500"},{time:'3 year',price:"3750"}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
},   
 {
    id:2,
    primaryColor:"#FFF",
    benefitColor:'#706C6E',
    textColor:'#000',
    buttonColor:'#000',
    dropdownColor:'#FFF',
    buttonTextColor:'#FFF',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
   buttonPlaceholder:"Subscribe Now",
   finalPrice:"450",
   benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"300"} ,{time:'2 year',price:"500"},{time:'3 year',price:"750"}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
},   
 {
    id:3,
    primaryColor:"#FFF",
    benefitColor:"#706C6E",
    textColor:'#000',
    buttonTextColor:'#FFF',
    dropdownColor:'#FFF',
    secondaryColor:'#000',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"450",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"34400"} ,{time:'2 year',price:"67500"}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
},   
 {
    id:4,
    primaryColor:"#FFF",
    benefitColor:"#706C6E",
    textColor:'#000',
    dropdownColor:'#FFF',
    buttonTextColor:'#FFF',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"450",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"3300"} ,{time:'2 year',price:"5200"},{time:'3 year',price:"7503"}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
},   
 {
    id:5,
    primaryColor:"#BE0A1F",
    secondaryColor:"#000",
    textColor:'#000',
    buttonTextColor:'#FFF',
    dropdownColor:'#FFF',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"450",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"3100"} ,{time:'2 year',price:"3500"},{time:'3 year',price:"1750"}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ] 
},   
]
export default data3;